# djangochat-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangochat-deployment
spec:
  replicas: 3  # Adjust the number of replicas based on your requirements for high availability
  selector:
    matchLabels:
      app: djangochat
  template:
    metadata:
      labels:
        app: djangochat
    spec:
      containers:
      - name: dchatcon
        image: dchatimg:latest  # Replace with the name of your Docker image
        ports:
        - containerPort: 8000
        # Add any environment variables or volume mounts if needed
---
apiVersion: v1
kind: Service
metadata:
  name: djangochat-service
spec:
  selector:
    app: djangochat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort  # Use LoadBalancer type if running on a cloud provider

